### ISSUE TITLE
1.4（10）在Catalina 上无法正常使用

### ISSUE THREAD

**Issue by yangcore** [michaellee123/EasyShare#2]
无法弹出二维码，1.2可以正常使用，希望增加分享文件夹功能

**Comment by michaellee123** [comment]
hello，目前1.4版本和1.3版本区别仅仅是logo适配了最新的big sur风格，1.3和1.2区别是在big sur上面有一个类型转换的地方于之前Catalina不同，我适配了big sur，但是因为我电脑已经升级到big sur了，没有办法去测试到Catalina的使用，但是功能上是没有区别的，建议你先用1.2版本。
至于分享文件夹这个功能，我没有打算做，文件夹文件多的情况下传输速度得不得保证，不如zip之后再分享，关于文件夹方面，我有另一个想法，用于接收文件使用，但是目前有遇到一些技术问题还没解决。
感谢支持！祝工作顺利，身体健康。
