### ISSUE TITLE
1.5（11）默认网络切换场景需求

### ISSUE THREAD

**Issue by Hollz** [michaellee123/EasyShare#3]
在办公场景 Mac mini 连了Wifi 和 网线(内网)，分享的时候默认以太网。但接收的设备连不上内网，需要拔网线或者停用网卡才可以切换到Wifi 同一局域网下。希望默认取网络的优先级 或者手动切换开关。
![截屏2023-11-04 10 05 26](https://github.com/michaellee123/EasyShare/assets/7620506/6d9f8b4e-7caf-4d97-a438-4b3b2b9f1c5c)

**Comment by michaellee123** [comment]
我仔细看了一下这个情况，首先可以肯定的是你不需要拔网线也能访问。可以参考这个链接： [Perfect Doc](https://github.com/PerfectlySoft/PerfectDocs/blob/master/guide.zh_CN/HTTPServer.md#address地址) 我没有设置address参数，所以它会监听你所有的网卡地址。

然后现在这个问题出在我展示UI界面的时候默认只显示了第一个IP地址（获取了一个列表，但是取了index=0），因为我这里的网络情况，我只有Wi-Fi可以连，目前想到了解决方法，就是在显示之前判断如果有多个就先选择一下IP再显示，不过我暂时没办法模拟这个场景，就算写了代码也没办法测试，可能要等一段时间才能加上这个功能。

再然后，现在有两个办法可以临时解决，第一个比较傻，就是扫码之后手动改一下手机这边的IP到Mac这边Wi-Fi的IP地址。第二个就是在Mac这边跑一个nginx把以太网的12580端口请求转发到Wi-Fi这边来，我觉得用第二种方法应该会更方便，只不过可能需要一点学习成本。

这里有一些文档，我简单扫了一眼应该是对的 [Install](https://pimylifeup.com/install-nginx-on-macos/#controlling-nginx-on-macos) [Config](https://www.cnblogs.com/hukey/p/11868017.html)

**Comment by Hollz** [comment]
有空可以加下

**Comment by michaellee123** [comment]
> 有空可以加下

我有时间的时候看看，最近沉迷游戏了😄，你先配置一个nginx临时解决一下吧
